mac/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    

    path("", views.index, name="index"),

    path("add_cart/<int:myid>/", views.add_cart, name="add_cart"),
    path("update_cart/<int:myid>/<oper>/", views.update_cart, name="update_cart"),  

    path("search/", views.search, name="search"), 
    
   
    path("products/<int:myid>", views.productView, name="ProductView"),

    path("checkout/", views.checkout, name="Checkout"),

    path("about/", views.about, name="AboutUs"),
    path("contact/", views.contact, name="ContactUs"),

    path("<cat_name>/", views.shop, name="home"),

   
]

shop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300,default="nothing is to describe")
    pub_date = models.DateField()
    image = models.ImageField(upload_to='shop/images', default="")
    cart=models.BooleanField(default=False)
    qty=models.IntegerField(default=0)
    total=models.IntegerField(default=1)


    def __str__(self):
        return self.product_name

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")


    def __str__(self):
        return self.name

class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=5000,default='none')
    qty=models.IntegerField(default=0)
    name = models.CharField(max_length=111)
    phone = models.CharField(max_length=70, default="")
    email = models.CharField(max_length=70, default="")
    state = models.CharField(max_length=111)
    zip_code = models.CharField(max_length=111)
    city = models.CharField(max_length=111)
    address = models.CharField(max_length=11)
    pub_date = models.DateTimeField(default=timezone.now)
    # created_at = models.DateTimeField(False, True, editable=False)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render,redirect
from .models import Product, Contact, Orders
from math import ceil
import json
from django.http import HttpResponse
# Create your views here.

def add_cart(request,myid):
   total=0
   pro=Product.objects.filter(id=myid)
   for q in pro:
        pro_cat=q.category
        qty=q.qty
        price=q.price
       
   qty=qty+1
   total=qty*price
   pro.update(cart=True,qty=qty,total=total)
   return redirect('shop:home',cat_name=pro_cat)


def update_cart(request,myid,oper):
    pro=Product.objects.filter(id=myid)
    for q in pro:
        pro_cat=q.category
        qty=q.qty
        total=q.total
        price=q.price

    if oper=='minus':
        qty=qty-1
        if qty==0:
            pro.update(qty=0,total=0,cart=False)
        total=qty*price
        pro.update(qty=qty,total=total)
    else:
        qty=qty+1
        total=qty*price
        pro.update(qty=qty,total=total)

    return redirect('shop:home',cat_name=pro_cat)

def index(request):
    return render(request, 'shop/home.html')

def shop(request,cat_name):
    allProds = []
    prod = Product.objects.filter(category=cat_name)
    n = len(prod)
    nSlides = n // 4 + ceil((n / 4) - (n // 4))
    allProds.append([prod, range(1, nSlides), nSlides])
    params = {'allProds':allProds}
    return render(request, 'shop/index.html', params)


def about(request):
    return render(request, 'shop/about.html')


def contact(request):
    if request.method=="POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
    return render(request, 'shop/contact.html')


def tracker(request):
   return render(request, 'shop/tracker.html')


def search(request):
    # return HttpResponse('helllo searched page is here!')
    searched=request.GET.get('q')
    products=Product.objects.filter(product_name__contains=searched)
    return render(request, 'shop/search.html',{'products':products})


def productView(request, myid):

    # Fetch the product using the id
    product = Product.objects.filter(id=myid)
    return render(request, 'shop/prodView.html', {'product':product[0]})


def checkout(request):
    qty=0
    item=''
    every=''
    data=Product.objects.filter(qty__gt=0)
    for d in data:
        qty=d.qty
        item=d.product_name
        every=every+item+'--'+str(qty)+','

    total=0
    for i in data:
        total+=i.total
    if request.method=="POST":
        items_json = request.POST.get('itemsJson', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        address = request.POST.get('address1', '') + " " + request.POST.get('address2', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('zip_code', '')
        phone = request.POST.get('phone', '')
        order = Orders(items_json=every,qty=qty,name=name, email=email, address=address, city=city,
                       state=state, zip_code=zip_code, phone=phone)
        order.save()
        thank = True
        data=Product.objects.filter(qty__gt=0)
        data.update(qty=0,cart=False,total=0)
        return render(request, 'shop/checkout.html',{'thank':thank})
    return render(request, 'shop/checkout.html',{'data':data,'total':total})

shop/templates/shop/about.html
{% extends 'shop/basic.html' %}

{% block title%} About Us{% endblock %}
{% block body %}




<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">My Awesome Cart!</h1>
      <p>My Awesome Cart Pvt Ltd. is an Indian electronic commerce company based in Bengaluru, India. Founded by Sachin Bansal and Binny Bansal in 2007, the company initially focused on book sales, before expanding into other product categories such as consumer electronics, fashion, and lifestyle products.

The service competes primarily with Amazon' s Indian subsidiary, and the domestic rival Snapdeal.[5][6] as of March 2017, Flipkart held a 39.5% market share of India's e-commerce industry.[7] Flipkart is significantly dominant in the sale of apparel (a position that was bolstered by its acquisitions of Myntra and Jabong.com), and was described as being "neck and neck" with Amazon in the sale of electronics and mobile phones.[8] Flipkart also owns PhonePe, a mobile payments service based on the Unified Payments Interface (UPI).

In August 2018, U.S.-based retail chain Walmart acquired a 77% controlling stake in Flipkart for US$16 billion, valuing it at $22 billion.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>





{% endblock %}

shop/templates/shop/basic.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
     <style>
       {% block css %} {% endblock %}
  </style>
  </head>
  <body style = "background-color : #F4F7FC">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Online Bakery Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/shop/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/shop/contact">Contact Us <span class="sr-only">(current)</span></a>
      </li>
     
     
      
    </ul>
    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'shop:search' %}">
      <input class="form-control mr-sm-2" type="search" name="q"   placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
   <button type="button" class="btn btn-secondary mx-2" id="popcart" data-container="body" data-toggle="popover" data-placement="bottom" data-html="true" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">
  Cart(<span id="cart">0</span>)
</button>
  </div>
</nav>
  {% block body %} {% endblock %}

 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
  </body>
</html>   

shop/templates/shop/checkout.html
{% extends 'shop/basic.html' %}
{% block title%} Checkout - My Awesome Cart{% endblock %}
{% block body %}
<div class="container">
    <div class="col my-4">
        <h2>Step 1 - My Awesome Cart Express Checkout - Review Your Cart Items</h2>
        {% if thank %}
        <h1>Your order is palced successfully</h1>
        {% else %}
        <table class="table">
            
            <thead>
            <tr>
               <th scope="col">SNo</th> 
              <th scope="col">Product</th>
              <th scope="col">Qty</th>
              <th scope="col">price</th>


            </tr>
           </thead>
           <tbody>
        {% if data %}
        {{total}}
                {% for i in data %}
                <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{i.product_name}}</td>
                 <td>{{i.qty}}</td>
                 <td>{{i.price}}</td>
              
               
                
                </tr>
                {% endfor %}
        {% endif %}
        <th scope="col"></th> 
              <th scope="col"></th>
              <th scope="col"></th>
              <th scope="col"></th>
        <th scope="col">Total:{{total}}</th>
        </tbody>
        </table>
        {% endif %}
        
    </div>
    <div class="col my-4">
        <h2>Step 2 - Enter Address & Other Details:</h2>
        <form method="post" action="/shop/checkout/">
            {% csrf_token %}
            <input type="hidden" name="itemsjson" id="itemsjson">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputname">Name</label>
                    <input type="name" name="name" class="form-control" id="name" placeholder="Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Email" name="email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" name="address1" class="form-control" id="address1" placeholder="1234 Main St">
            </div>
            <div class="form-group">
                <label for="inputAddress2">Address line 2</label>
                <input type="text" name="address2" class="form-control" id="address2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputCity">City</label>
                    <input type="text" class="form-control" id="city" name="city">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="state" placeholder="Enter State" name="state">
                </div>
                <div class="form-group col-md-2">
                    <label for="inputZip">Zip</label>
                    <input type="text" class="form-control" id="zip_code" name="zip_code">
                </div>
            </div>
            <div class="form-group">
                    <label for="inputZip">Phone Number</label>
                    <input type="tel" class="form-control" id="phone" name="phone"> 
                </div>
            <button type="submit" class="btn btn-primary">CheckOut</button>
        </form>
    </div>
</div>
{%if thank %}

{% endif %}
{% endblock %}

shop/templates/shop/contact.html
{% extends 'shop/basic.html' %}

{% block title%} Contact Us - My Awesome Cart{% endblock %}
{% block body %}
<div class="container my-3">
    <h1 class = text-center style = "font-family : 'Monotype Corsiva' ; color : #E6120E">Contact Us</h1>
    <form action="/shop/contact/" method="post">{% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name='name' placeholder="Enter Your Name">
  </div>
  <div class="form-group">
    <label for="name">Email</label>
    <input type="email" class="form-control" id="email" name='email' placeholder="Enter Your Email">
  </div>

    <div class="form-group">
    <label for="name">Phone</label>
    <input type="tel" class="form-control" id="phone" name='phone' placeholder="Enter Your Phone Number">
  </div>


   <div class="form-group">
    <label for="desc">How May We Help You?</label>
    <textarea class="form-control" id="desc" name='desc' rows="3"></textarea>
  </div>
        <button type="submit" class="btn btn-success">Submit</button>
</form>



</div>
{% endblock %}

shop/templates/shop/home.html
{% extends 'shop/basic.html' %}

{% block title%}Home Page{% endblock %}
{% block body %}
<style type="text/css">
  img{
    width: 200px;
    height: 300px;
    padding: 20px;
    
  }
  .card{
    padding: 20px;
    margin: 100px;
  }
</style>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/media/shop/images/1.jpg" style = "width : 100% ; height : 450px">
     

    </div>
    <div class="carousel-item">
      <img src="/media/shop/images/2.jpg" style = "width : 100% ; height : 450px">
    
    </div>
    <div class="carousel-item">
      <img src="/media/shop/images/3.jpg"  alt="..." style = "width : 100% ; height : 450px">
     
    </div>
    <div class="carousel-item">
      <img src="/media/shop/images/4.jpg"  alt="..." style = "width : 100% ; height : 450px">
    
    </div>
	
	 <div class="carousel-item">
      <img src="/media/shop/images/5.jpg"  alt="..." style = "width : 100% ; height : 450px">
    
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">

  <div class="row">

 <a href="/shop/cake">
      <div  class="card" style="width: 18rem;">
   <img src="/media/shop/images/c1.jpg"  alt="...">
  <div class="card-body">
    <h5 class="card-title">Cakes</h5>
    <p class="card-text">Cakes are special. Every birthday, every celebration ends with something sweet, a cake, and people remember. It's all about the memories.</p>
    <a href="#" class="btn btn-primary">View Cakes</a>
  </div>
</div>

 </a>

<a href="/shop/biscuit">
  <div class="card" style="width: 18rem;">
   <img src="/media/shop/images/b1.jpg"  alt="...">
  <div class="card-body">
    <h5 class="card-title">Biscuits</h5>
    <p class="card-text">Money can't buy you love, but it can get you some really good chocolate ginger biscuits..</p>
    <a href="#" class="btn btn-primary">View Biscuits</a>
  </div>
</div>
</a>

<a href="/shop/namkeen">
  <div class="card" style="width: 18rem;">
   <img src="/media/shop/images/n1.jpg"  alt="...">
  <div class="card-body">
    <h5 class="card-title">Namkeen</h5>
    <p class="card-text">The ultimate Indian snack – namkeens - are truly hard to resist. Every household will always have a packet of namkeen in their house to munch on at odd hours.</p>
    <a href="#" class="btn btn-primary">View Namkeens</a>
  </div>
</div>
</a>

<a href="/shop/sweet">
  <div class="card" style="width: 18rem;">
   <img src="/media/shop/images/m1.jpg"  alt="...">
  <div class="card-body">
    <h5 class="card-title">Sweets</h5>
    <p class="card-text">There is no better way to bring people together than with desserts.</p>
    <a href="#" class="btn btn-primary">View Sweets</a>
  </div>
</div>
</a>


  </div>



</div>


{% endblock %} 

shop/templates/shop/index.html
{% extends 'shop/basic.html' %}
{% block css %}
.col-md-3
{
display: inline-block;
margin-left:-4px;
}
img{
    width: 100px;
    height: 200px;
    padding: 2px;
    margin: 30px;
  }
.carousel-indicators .active {
background-color: blue;
}
.col-md-3 img{
width: 170px;
height: 200px;
}
body .carousel-indicator li{
background-color: blue;
}
body .carousel-indicators{
bottom: 0;
}
body .carousel-control-prev-icon,
body .carousel-control-next-icon{
background-color: blue;
}
.carousel-control-prev,
.carousel-control-next{
top: auto;
bottom: auto;
padding-top: 222px;
}
body .no-padding{
padding-left: 0,
padding-right: 0;
}
{% endblock %}
{% block body %}
{% load static %}
<div class="container">
    <!--Slideshow starts here -->
    {% for product, range, nSlides in allProds %}
    <h5 class="my-4">Flash Sale On {{product.0.category}} - Recommended Items</h5>
    <div class="row">
        <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>
                {% for i in range %}
                <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
                {% endfor %}
            </ul>
            <div class="container carousel-inner no-padding">
                <div class="carousel-item active">

                    {% for i in product %}
                    
                    <div class="col-xs-3 col-sm-3 col-md-3">
                        <div class="card align-items-center" style="width: 18rem;">
                            <img src='/media/{{i.image}}' class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title" id="namepr{{i.id}}">{{i.product_name}}</h5>
                                <p id="pricepr{{i.id}}">{{i.price}}</p>
                                <p class="card-text">{{i.desc|slice:"0:53"}}...</p>
                                
                                {% if i.cart %}
                                <a href="/shop/update_cart/{{i.id}}/minus"><button id='minus" + item + "' class='btn btn-primary minus'>-</button> </a>
                                <span>{{i.qty}}</span> 
                               <a href="/shop/update_cart/{{i.id}}/plus"> <button id='plus" + item + "' class='btn btn-primary plus'> + </button></a>

                                {% else %}
                                <span id="divpr{{i.id}}" class="divpr">
                                    <a href="{% url 'shop:add_cart' i.id %}"><button id="pr{{i.id}}" class="btn btn-primary cart" >Add To Cart</button></a>
                                </span>
                                {% endif %}

 


                                <a href="/shop/products/{{i.id}}"><button id="qv{{i.id}}" class="btn btn-primary cart">QuickView</button></a>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
                </div>
                <div class="carousel-item">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- left and right controls for the slide -->
        <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}
{% block js %}
<script>
     $('#popcart').popover();
      popStr =  "</div> <a href='/shop/checkout'><button class='btn btn-primary' id ='checkout'>Checkout</button>"
      // "</a> <button class='btn btn-primary' onclick='clearCart()' id ='clearCart'>Clear Cart</button>     "
    document.getElementById('popcart').setAttribute('data-content', popStr);

     $('#popcart').popover('show');
</script>
{% endblock %}

shop/templates/shop/prodView.html
{% extends 'shop/basic.html' %}

{% block title%} {{product.product_name}} - My Awesome Cart{% endblock %}
{% block body %}
<div class="container my-4">
    <div class="row">
    <div class="col-md-4">
    <div class="row">
        <img src="/media/{{product.image}}" width="233px" height="385px">
    </div>
        <div class="row my-4">
           <a href="{% url 'shop:add_cart' product.id %}"> <button class="btn btn-primary mx-3">Add To Cart</button></a>
            <button class="btn btn-primary">Buy Now</button>
        </div>

    </div>

    <div class="col-md-8">
        <h5>{{product.product_name}}</h5>
        <p><b>Rs.{{product.price}} </b></p>
        <p>{{product.desc}}</p>


    </div>
    </div>


</div>




{% endblock %}




{% block js %}
<script>
console.log('working');
if(localStorage.getItem('cart') == null){
var cart = {};
}
else
{
cart = JSON.parse(localStorage.getItem('cart'));
document.getElementById('cart').innerHTML = Object.keys(cart).length;
}
$('.cart').click(function(){
console.log('clicked');
var idstr = this.id.toString();
console.log(idstr);
if (cart[idstr] !=undefined){
cart[idstr] = cart[idstr] + 1;
}
else
{
cart[idstr] = 1;
}
console.log(cart);
localStorage.setItem('cart', JSON.stringify(cart));
document.getElementById('cart').innerHTML = Object.keys(cart).length;
});
$('#popcart').popover();
document.getElementById("popcart").setAttribute('data-content', '<h5>Cart for your items in my shopping cart</h5>');
</script>
{% endblock %}

shop/templates/shop/search.html
{% extends 'shop/basic.html' %}

{% block title%} About Us{% endblock %}
{% block body %}

<style type="text/css">
    img{
    width: 10px;
    height: 300px;
    padding: 10px;
    margin: 10px;
  }
</style>
<div class="container">
<div class="row">
{% for i in products %}
 <div class="col-xs-3 col-sm-3 col-md-3">
                        <div class="card align-items-center" style="width: 18rem;">
                            <img src='/media/{{i.image}}' class="card-img-top " alt="...">
                            <div class="card-body">
                                <h5 class="card-title" id="namepr{{i.id}}">{{i.product_name}}</h5>
                                <p id="pricepr{{i.id}}">{{i.price}}</p>
                                <p class="card-text">{{i.desc|slice:"0:53"}}...</p>
                                
                                {% if i.cart %}
                                <a href="/shop/update_cart/{{i.id}}/minus"><button id='minus" + item + "' class='btn btn-primary minus'>-</button> </a>
                                <span>{{i.qty}}</span> 
                               <a href="/shop/update_cart/{{i.id}}/plus"> <button id='plus" + item + "' class='btn btn-primary plus'> + </button></a>

                                {% else %}
                                <span id="divpr{{i.id}}" class="divpr">
                                    <a href="{% url 'shop:add_cart' i.id %}"><button id="pr{{i.id}}" class="btn btn-primary cart" >Add To Cart</button></a>
                                </span>
                                {% endif %}

 


                                <a href="/shop/products/{{i.id}}"><button id="qv{{i.id}}" class="btn btn-primary cart">QuickView</button></a>
                            </div>
                        </div>
                    </div>
{% endfor %}
</div>
</div>

{% endblock %}